global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Métricas do seu Scanner Pro (FastAPI)
  - job_name: 'scanner-api'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Métricas do Prometheus (auto-monitoring)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Métricas do Redis via exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Métricas do próprio Grafana (opcional)
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
